services:
  - type: web
    name: schoolconnect-web
    runtime: docker
    plan: free
    region: singapore
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: SchoolConnect__PortalAuth__Admin__Pin
        value: ADMIN
      - key: SchoolConnect__PortalAuth__Admin__Password
        sync: false
      - key: ConnectionStrings__SchoolConnectDb
        fromDatabase:
          name: schoolconnect-db
          property: connectionString

databases:
  - name: schoolconnect-db
    databaseName: schoolconnect
    region: singapore
    plan: basic-256mb
    ipAllowList: []
